version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-pix
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pix
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pix-network

  redis:
    image: redis:latest
    container_name: redis-pix
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no", "--loglevel", "debug"]
    ports:
      - "6379:6379"
    networks:
      - pix-network

  pix-app:
    build:
      context: ../pix
      dockerfile: Dockerfile
    image: pix-app:latest
    container_name: pix-app-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_REDIS_HOST: redis-pix
      SPRING_REDIS_PORT: 6379
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 12h
    networks:
      - pix-network
    depends_on:
      - postgres
      - redis

networks:
  pix-network: 
    driver: bridge

volumes:
  postgres-data:
